rabbit-client:
  image: ihciah/rabbit
  ports:
    - "9892:443/tcp"
  environment:
    - MODE=c
    - PASSWORD=password
    - RABBITADDR=your.rabbit.server:9891
    - LISTEN=:443
    - DEST=your.service:port
    - TUNNELN=6
    - VERBOSE=2
  restart: always